### ISSUE TITLE
Page jump when using sticky nav

### ISSUE THREAD

**Issue by dchacon1** [radancyco/tb-ajd-template#4]
Every time you click on a section of the sticky nav the page jumps then scrolls to the appropriate section. Can you please make it so the page doesn't jump first. I believe the issues has to do with this section of the code:    
// // changes focus to section
    $(selector).attr('tabindex', '-1').focus();

once you remove this code the nav works without the page jump, but since it is removed it doesn't focus on the section.

**Comment by michaelspellacy** [comment]
Hi @dchacon1 that is integral functionality for accessibility, so it should not be removed. I don't see the issue you are describing in the boilerplate located here: https://tmpworldwide.github.io/tb-ajd-template/examples/skeleton/ Does it exist there? Maybe I'm missing something.

**Comment by dchacon1** [comment]
Yes it does occur in the link you referenced. I tried it with my mobile phone. But I am confident it occurs on desktop too as that is where initially found the error.  It is a split second page jump and only happens if you click a link in the overview nav section. For example, when you first load the page and click trending the page jumps and then goes to the appropriate section.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Brockenstein** [comment]
@michaelspellacy  I know about the issue @dchacon1 is talking about and have a fix in the works. I just asked him to add the issue so that in Janurary when I have a spare moment I have a reminder of what I need to update in the AJD script.

**Comment by Brockenstein** [comment]
Fixed this issue and closing ticket. 

Just a heads up to @dchacon1  and @michaelspellacy  the reason for this slight jump was indeed the focus change. I attempted to have the focus change wait to happen after the scroll to had completed but that just threw off the offset. So what I have concluded is when you need to change focus during a scroll to it is best to disable the focus from changing the screen position. you can do this via the following code:

```
// Prevent viewport from jumping to focus
var position = $(window).scrollTop();
$('#your-element').focus()
$(window).scrollTop(position);
```

**Comment by dchacon1** [comment]
I just realized you sent this message. I sent it to everyone on slack,  the one I sent though works for pages outside of ajds.. however out still doesn't work on ie11. But oh well

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Brockenstein** [comment]
@dchacon1 I agree "oh well" since I am not able to consistently recreate the problem on ie11 and this solution appears to be working in all modern browsers I think we will leave this one as fixed. I may however look into throttling the scroll triggers and make sure that is not causing and issue.
